#!/usr/bin/env bash
set -eu

CHRONY_CONF_FILE="/etc/chrony/chrony.conf"
DEFAULT_NTP="0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org,3.pool.ntp.org"

# Confirm correct permissions on chrony run directory
if [ -d /run/chrony ]; then
  chown -R chrony:chrony /run/chrony
  chmod 0750 /run/chrony
fi

# Remove previous pid file if it exists
rm -f /run/chrony/chronyd.pid /var/run/chrony/chronyd.pid

# Confirm correct permissions on chrony variable state directory
if [ -d /var/lib/chrony ]; then
  chown -R chrony:chrony /var/lib/chrony
fi

rm -f "$CHRONY_CONF_FILE"
touch "$CHRONY_CONF_FILE"
chown chrony:chrony "$CHRONY_CONF_FILE"

# Dynamically populate chrony config file.
{
  echo "# https://github.com/dockur/chrony"
  echo
  echo "# chrony.conf file generated by startup script"
  echo
  echo "# Time servers provided by NTP_SERVERS environment variable."
} >> "$CHRONY_CONF_FILE"

# NTP_SERVERS environment variable is not present, so populate with default server
if [ -z "${NTP_SERVERS:-}" ]; then
  NTP_SERVERS="$DEFAULT_NTP"
fi

# LOG_LEVEL environment variable is not present, so populate with chrony default (0)
# chrony log levels: 0 (informational), 1 (warning), 2 (non-fatal error) and 3 (fatal error)
if [ -z "${LOG_LEVEL:-}" ]; then
  LOG_LEVEL=0
else
  # Confirm log level is between 0-3, since these are the only log levels supported
  case "$LOG_LEVEL" in
    0|1|2|3) ;;
    *) LOG_LEVEL=0 ;;
  esac
fi

# Add NTP servers
{
  printf "%s" "$NTP_SERVERS" | tr ',' '\n' | while IFS= read -r N; do

    # Strip quotes and surrounding whitespace from ntp server
    N_CLEANED=$(
      printf "%s" "$N" |
        tr -d '"' |
        sed 's/^[[:space:]]*//; s/[[:space:]]*$//'
    )

    # Skip empty entries
    [ -z "$N_CLEANED" ] && continue

    # Check if ntp server has a 127.0.0.0/8 address indicating it's
    # the local system clock
    case "$N_CLEANED" in
      127.*)
        echo "server $N_CLEANED"
        echo "local stratum 10"
        ;;

      *)
        if [ "${ENABLE_NTS:-false}" = true ]; then
          echo "server $N_CLEANED iburst nts"
        else
          echo "server $N_CLEANED iburst"
        fi
        ;;
    esac

  done
} >> "$CHRONY_CONF_FILE"

# PTP0 configuration: if it has been passed through, it means we want to use it
if [ -e /dev/ptp0 ]; then
  echo "refclock PHC /dev/ptp0 poll 3 dpoll -2 stratum 2" >> "$CHRONY_CONF_FILE"
fi

# Final bits for the config file
{
  echo
  echo "driftfile /var/lib/chrony/chrony.drift"
  echo "makestep 0.1 3"

  if [ -n "${NTP_DIRECTIVES:-}" ]; then
    printf "%b\n" "$NTP_DIRECTIVES"
  fi

  if [ "${NOCLIENTLOG:-false}" = true ]; then
    echo "noclientlog"
  fi

  echo
  echo "allow all"
} >> "$CHRONY_CONF_FILE"

args=(
  -U
  -u chrony
  -d
  -L "$LOG_LEVEL"
)

# Enable control of system clock, disabled by default
if [ "${ENABLE_SYSCLK:-false}" != true ]; then
  args+=(-x)
fi

if [ ! -f /proc/net/if_inet6 ] || [ "$(cat /proc/sys/net/ipv6/conf/all/disable_ipv6 2>/dev/null || echo 0)" = "1" ]; then
  args+=(-4)
fi

# Startup chronyd in the foreground
exec /usr/sbin/chronyd "${args[@]}"
