on:
  push:
    branches-ignore:
      - master
    paths:
      - '**/*.sh'
      - 'Dockerfile'
      - 'Dockerfile.custom'

  pull_request:
    paths:
      - '**/*.sh'
      - 'Dockerfile'
      - 'Dockerfile.custom'

name: "Test"
permissions: {}

jobs:
  shellcheck:
    name: Test
    uses: ./.github/workflows/check.yml
